### ISSUE TITLE
Wrong architecture deb file rigenera-app_1.3.0_i386.deb

### ISSUE THREAD

**Issue by gtoverloaded** [OpenGenova/welcomerigenera#1]
Il file deb  rigenera-app_1.3.0_i386.deb è per architetture  X86-64 invece di architetture  i686.

**Comment by enri-ge** [comment]
@gtoverloaded ho [aggiunto i file .deb ](https://github.com/OpenGenova/welcomerigenera/tree/master/build-app)per entrambe le architetture. Puoi verificare che funzioni l'installazione?

**Comment by anaselli** [comment]
Non funziona, alla fine l'ho generato per i386 e sembra installare. Il problema è che il pacchetto comunque non mostra ciò che si vede usando `npm start `sui sorgenti

**Comment by anaselli** [comment]
Ok i pacchetti che ho ricostruito ora vanno. Ho creato la prima release 1.3.1. Le release sono rilasciate [qui](https://github.com/OpenGenova/welcomerigenera/releases)
